###

POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "email": "lala@stis.ac.id",
  "password": "lalala",
  "userRole": "admin"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "makanenak"
}

###
POST http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzA5NzEzMjE0LCJleHAiOjE3MDk3OTk2MTR9.boneJjMBfxphMT0ggOnYZpkq2N8IwEZbM1_vM4DhAGo

###
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzA5NzEzMjE0LCJleHAiOjE3MDk3OTk2MTR9.boneJjMBfxphMT0ggOnYZpkq2N8IwEZbM1_vM4DhAGo

###
GET http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MDg3OTI4NDIsImV4cCI6MTcwODg3OTI0Mn0.CnsttFzMtQ0n6ZPKA9BHFEBllMbXblBeOO6pA_K1HOE

###
GET http://localhost:3000/api/users/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MDg3NjE3MzksImV4cCI6MTcwODg0ODEzOX0.z61SDdOby882_QmcY048rwguoXF_uTbdywfQjbFyQYk

###
PUT http://localhost:3000/api/users/update/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MDg3NjE3MzksImV4cCI6MTcwODg0ODEzOX0.z61SDdOby882_QmcY048rwguoXF_uTbdywfQjbFyQYk

{
  "email": "tyo@stis.ac.id",
  "password": "password"
}

###
GET http://localhost:3000/mahasiswa?tahun=2023%2F2024&nim=741146864
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzA5MTkwNDIyLCJleHAiOjE3MDkyNzY4MjJ9.lQBheMikGKJ8R2MaLhxkmh_qXvr6ElypIIxrfJmcNTE

###
PUT http://localhost:3000/mahasiswa/889887838
Content-Type: application/json

{
  "dosenPembimbingMagang": {
    "nip": "091708548"
  },
  "pembimbingLapangan": {
    "nip": "353757282"
  },
  "satker": {
    "kode": "5604"
  },
  "alamat": "Jl. Raya Bogor, Bogor, Jawa Barat, Indonesia",
}

###
DELETE http://localhost:3000/mahasiswa/889887838

###
POST http://localhost:3000/mahasiswa/excel
Content-Type: multipart/form-data

{
  "file": "C:/Users/Rahmad Setiya Budi/Documents/app/backend-magang/test-mahasiswa.xlsx"
}

###
GET http://localhost:3000/dosen-pembimbing

###
Put http://localhost:3000/dosen-pembimbing/455768196
Content-Type: application/json

{
  "email": "dosenksss@gmail.com",
  "user": {
    "email": "ganti@gmail.com"
  }
}

###
POST  http://localhost:3000/dosen-pembimbing
Content-Type:  application/json

{
  "nip": "091708548",
  "nama": "Bebas",
  "prodi": "DIV Komputasi Statistik",
  "user" : {
    "email": "bebas@gmail.com",
    "password": "bebas"
  }
}


###
Get http://localhost:3000/dosen-pembimbing/455768196/mahasiswa

###
GET http://localhost:3000/pembimbing-lapangan/353757282/mahasiswa

###
GET http://localhost:3000/satker?kodeProvinsi=63&internalBPS=1

###
POST http://localhost:3000/satker
Content-Type:  application/json

{
  "nama": "BPS Kabupaten Kediri",
  "alamat": "Jl. Raya Kediri, Kediri, Jawa Timur, Indonesia",
  "email": "bps5604@bps.go.id",
  "kabupatenKota": {
    "nama": "Kediri",
    "provinsi": {
      "nama": "Jawa Timur"
    }
  },
  "kode": "5604",
  "kapasitas": 5,
  "internalBPS": true
}

###
POST http://localhost:3000/pemilihan-penempatan
Content-Type:  application/json

{
  "mahasiswa": {
    "nama": "John Doe",
    "nim": 123,
    "alamat": "Jl. Raya Pajajaran No. 1, Bogor"
  },
  "satker": {
    "kodeSatker1": "1234",
    "kodeSatker2": "5678",
    "kodeSatker3": "9101"
  },
  "status": "Menunggu"
}

###
POST http://localhost:3000/bimbingan-magang
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzA5Mzk3MjQ5LCJleHAiOjE3MDk0ODM2NDl9.cY0diflxJqvWcK4lsbb22JZ1gKdIKow09gBumz_WmHg

# created by mahasiswa
{
  "tanggal": "2021-08-01",
  "tempat": "link zoom"
}

# cretaed by dosen
# {
#   "tanggal": "2021-08-01",
#   "tempat": "banyak mahasiswa",
#   "peserta": [
#     {
#       "nim": "073256633"
#     },
#     {
#       "nim": "834867542"
#     }
#   ]

# }

###
PUT http://localhost:3000/bimbingan-magang/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzA5Mzk3MjQ5LCJleHAiOjE3MDk0ODM2NDl9.cY0diflxJqvWcK4lsbb22JZ1gKdIKow09gBumz_WmHg

{
  "tanggal": "2021-08-01",
  "tempat": "link zoom dong"
}

###
GET http://localhost:3000/bimbingan-magang/dosen-pembimbing/491718953

###
GET http://localhost:3000/bimbingan-magang/mahasiswa/586531010