###

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "admin@stis.ac.id",
  "password": "lalala",
  "userRole": "admin"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "admin"
}

###

PUT http://localhost:3000/users/update/2
Content-Type: application/json

{
  "email": "tyo@stis.ac.id",
  "password": "qwqwqw"
}

###
GET http://localhost:3000/users 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MDg3MDk2NjEsImV4cCI6MTcwODc5NjA2MX0.M4KmgLy8u7pljN9PmC7dmLNAV0s_s45_2C4T3hkk3Rc

###
DELETE http://localhost:3000/users/delete/3

###
GET http://localhost:3000/users/pemlap

###
GET http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MDg3MDk2NjEsImV4cCI6MTcwODc5NjA2MX0.M4KmgLy8u7pljN9PmC7dmLNAV0s_s45_2C4T3hkk3Rc

###
POST http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MDg3MDk2NjEsImV4cCI6MTcwODc5NjA2MX0.M4KmgLy8u7pljN9PmC7dmLNAV0s_s45_2C4T3hkk3Rc