###

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "lala@stis.ac.id",
  "password": "lalala"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "lala@stis.ac.id",
  "password": "lalala"
}

###

PUT http://localhost:3000/users/update/2
Content-Type: application/json

{
  "email": "tyo@stis.ac.id",
  "password": "qwqwqw"
}

###
GET http://localhost:3000/users

###
DELETE http://localhost:3000/users/delete/3